apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: access-secret
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/access-secret/access-secret.yaml
    options: {}
    type: Yaml
  drift:
    enabled: false
  namespace: newns
  placement:
    selector: rafay.dev/clusterName=mini
  version: access-secret-v3
