apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: multiyaml
  project: defaultproject
spec:
  artifact:
    artifact: {}
    options: {}
    type: Yaml
  drift:
    enabled: false
  namespace: newns
  placement: {}
