apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: multiyaml
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/multiyaml/multiyaml.yaml
    options: {}
    type: Yaml
  drift:
    enabled: false
  namespace: newns
  placement:
    selector: rafay.dev/clusterName=mini
