apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: test1
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/test1/test1.yaml
    options: {}
    type: Yaml
  drift:
    enabled: false
  namespace: newns
  placement:
    selector: rafay.dev/clusterName=mini
  version: test1-v1
