apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: test3
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/test3/test3.yaml
    options: {}
    type: Yaml
  drift:
    enabled: false
  namespace: newns
  placement:
    selector: rafay.dev/clusterName=mini
  version: test3-v1
