apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: test2
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/test2/test2.yaml
    options: {}
    type: Yaml
  drift:
    enabled: false
  namespace: newns
  placement:
    selector: rafay.dev/clusterName=mini
  version: test2-v2
