apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testallyaml
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/testallyaml/testallyaml.yaml
    options: {}
    type: Yaml
  drift:
    enabled: false
  namespace: newns
  placement:
    selector: rafay.dev/clusterName=mini
  version: testallyaml-v1
