apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: vault-tls-secret
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/vault-tls-secret/vault-tls-secret.yaml
    options: {}
    type: Yaml
  drift:
    enabled: false
  namespace: newns
  placement:
    selector: rafay.dev/clusterName=mini
  version: vault-tls-secret-v1
