apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: vault-testing
  project: defaultproject
spec:
  artifact:
    artifact: {}
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  drift:
    enabled: false
  namespace: newns
  placement: {}
