apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  id: rx28oml
  modifiedAt:
    nanos: 912843000
    seconds: 1634197949
  name: sync-job
  project: defaultproject
  projectID: rx28oml
spec:
  sharing: {}
  stages:
  - config:
      destinationRepo: {}
      gitToSystemSync: true
      includedResources:
      - name: '*'
      sourceAsDestination: true
      sourceRepo:
        repository: opatest
        revision: main
      systemToGitSync: true
    name: test
    type: SystemSync
