apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  id: rx28oml
  modifiedAt:
    nanos: 339357000
    seconds: 1634533399
  name: sync-job
  project: defaultproject
  projectID: rx28oml
spec:
  active: true
  sharing: {}
  stages:
  - config:
      destinationRepo: {}
      gitToSystemSync: true
      includedResources:
      - name: '*'
      sourceAsDestination: true
      sourceRepo:
        repository: opatest
        revision: main
      systemToGitSync: true
    name: test-ankit
    type: SystemSync
