apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-secret1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-secrets
  template:
    metadata:
      labels:
        app: vault-secrets
      annotations:
        rafay.dev/secretstore: vault
        vault.secretstore.rafay.dev/role: "demo"
        vault.secretstore.rafay.dev/filesecret-config-1: |
          {
            "vaultSecretRef": "app-secrets-v2/data/wordpress-mysql/data/data",
            "secretFileName": "secret-1",
            "volumeMountPath": "/secure/vault/secrets/1"
          }
    spec:
      serviceAccountName: vault-auth-demo
      containers:
      - name: alpine
        image: alpine:latest
        command: [ "/bin/ash", "-c", "--" ]
        args: [ "while true; do env; sleep 30; done;" ]
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: MYSQL_USERNAME
          value: secretstore:vault:app-secrets-v2/data/wordpress-mysql/data/data#data.username
        - name: MYSQL_PASSWORD
          value: secretstore:vault:app-secrets-v2/data/wordpress-mysql/data/data#data.password