apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedLimits
metadata:
  name: catorgorg
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    cpu: "200m"
    memory: "1Gi"
