apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  id: 4qkolkn
  modifiedAt:
    nanos: 191360000
    seconds: 1634533661
  name: new-sync-job
  project: defaultproject
  projectID: rx28oml
spec:
  sharing: {}
  stages:
  - config:
      destinationRepo:
        repository: opatest
        revision: main
      gitToSystemSync: true
      includedResources:
      - name: '*'
      sourceAsDestination: true
      sourceRepo:
        path:
          name: opatest/folder
        repository: opatest
        revision: main
      systemToGitSync: true
    name: test-ankit
    type: SystemSync
