apiVersion: opa.k8smgmt.io/v3
kind: Policy
metadata:
  name: name-test3
  project: defaultproject
spec:
  constraintList:
  - name: app-armor
  - name: linux-capabilities-drop-all
  - name: catorgorg
  excludedNamespaces:
  - namespaces:
    - name: default-rafay-system
    processes:
    - '*'
  installationParams:
    auditFromCache: true
    enableDeleteOperations: true
  sharing:
    enabled: true
    projects:
    - name: three
    - name: two
  version: ver4
