apiVersion: opa.k8smgmt.io/v3
kind: Policy
metadata:
  id: n7krp2l
  modifiedAt:
    nanos: 182279000
    seconds: 1636449149
  name: name-test2
  project: defaultproject
  projectID: rx28oml
spec:
  constraintList:
  - name: app-armor
  - name: linux-capabilities-drop-all
  - name: repo-is-openpolicyagent
  excludedNamespaces:
  - namespaces:
    - name: default-rafay-system
    processes:
    - '*'
  installationParams:
    auditFromCache: true
    enableDeleteOperations: true
  sharing:
    enabled: true
    projects:
    - id: 7w2lnkp
      name: three
    - id: 4qkolkn
      name: two
  version: v7
