apiVersion: opa.k8smgmt.io/v3
kind: Policy
metadata:
  id: gdk6g21
  modifiedAt:
    nanos: 418848000
    seconds: 1635912670
  name: shared
  project: defaultproject
  projectID: rx28oml
spec:
  constraintList:
  - {}
  - {}
  excludedNamespaces:
  - namespaces:
    - name: default-rafay-system
    processes:
    - audit
  installationParams:
    auditFromCache: true
    auditInterval: 60
    constraintViolationsLimit: 20
    enableDeleteOperations: true
  sharing:
    enabled: true
    projects:
    - id: 7w2lnkp
    - id: 4qkolkn
  syncObjects:
  - kind: Pod
    version: v1
  version: v2
