apiVersion: opa.k8smgmt.io/v3
kind: Policy
metadata:
  name: test-create12
  project: defaultproject
spec:
  constraintList:
  - name: app-armor
  - name: linux-capabilities-drop-all
  - name: catorgorg
  - name: repo-is-openpolicyagent
  excludedNamespaces:
  - namespaces:
    - name: default-rafay-system
    processes:
    - '*'
  installationParams:
    auditFromCache: true
    enableDeleteOperations: true
  sharing:
    enabled: true
    projects:
    - id: 7w2lnkp
      name: three
    - id: 4qkolkn
      name: two
  version: versionhere
