apiVersion: opa.k8smgmt.io/v3
kind: Policy
metadata:
  name: thisshouldwork
  project: defaultproject
spec:
  installationParams: {}
  sharing:
    enabled: true
    projects:
    - name: three
    - name: two
  version: v1
