apiVersion: opa.k8smgmt.io/v3
kind: ConstraintTemplate
metadata:
  id: 72d0gkg
  modifiedAt:
    nanos: 41584000
    seconds: 1635155553
  name: k8scontainerlimits
  project: defaultproject
  projectID: rx28oml
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/k8scontainerlimits/template1.yml
    options:
      disableOpenAPIValidation: true
      force: true
    type: Yaml
