apiVersion: opa.k8smgmt.io/v3
kind: ConstraintTemplate
metadata:
  id: yemp028
  modifiedAt:
    nanos: 409558000
    seconds: 1634757169
  name: k8sallowedrepos
  project: defaultproject
  projectID: rx28oml
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/k8sallowedrepos/temp.yml
    options: {}
    type: Yaml
