apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: serviceacc
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/serviceacc/serviceacc.yaml
    options: {}
    type: Yaml
  namespace: newns
  sharing:
    enabled: false
  version: serviceacc-v1
