apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: test2
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/test2/test2.yaml
    options: {}
    type: Yaml
  namespace: newns
  sharing:
    enabled: false
  version: test2-v1
