apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: test1
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/test1/test1.yaml
    options: {}
    type: Yaml
  namespace: newns
  sharing:
    enabled: false
  version: test1-v2
