apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: test2
  project: defaultproject
spec:
  artifact:
    artifact: {}
    options: {}
    type: Yaml
  namespace: newns
  sharing:
    enabled: false
