apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: vault-testing
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/vault-testing/vault-helm-0.5.0.tar.gz
      valuesPaths:
      - name: file://artifacts/vault-testing/vault-helm-050-values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: newns
  sharing:
    enabled: false
  version: vault-testing-v1
