apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: vault-tls-secret
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/vault-tls-secret/vault-tls-secret.yaml
    options: {}
    type: Yaml
  namespace: newns
  sharing:
    enabled: false
  version: vault-tls-secret-v2
