apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  description: asdasdasasdasd
  name: asdasd
  project: defaultproject
spec:
  defaultAddons:
    enableIngress: false
    enableLogging: false
    enableMonitoring: false
    enableVM: false
  drift:
    enabled: false
  sharing:
    enabled: false
