apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: rctl
  project: defaultproject
spec:
  defaultAddons:
    enableIngress: false
    enableLogging: false
    enableMonitoring: false
    enableVM: false
  drift:
    enabled: false
  sharing:
    enabled: false
