apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: rctl
  project: defaultproject
spec:
  base:
    name: minimal
    version: snapshot - 2021-11-26T04:20:39Z
  defaultAddons:
    enableIngress: true
    enableLogging: true
    enableMonitoring: true
    enableVM: false
  drift:
    enabled: false
  psp:
    enabled: true
    names:
    - rafay-privileged-psp
    scope: Cluster
  sharing:
    enabled: false
  version: v1
