apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: rctl-cli1
  project: defaultproject
spec:
  base:
    name: default
    version: snapshot - 2021-11-26T04:20:39Z
  defaultAddons:
    enableIngress: false
    enableLogging: true
    enableMonitoring: false
    enableVM: false
  drift:
    enabled: false
  sharing:
    enabled: false
  version: v1
