apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  description: df. erd wrdwdf v
  id: x3mxvkr
  modifiedAt:
    nanos: 392484000
    seconds: 1635419316
  name: test
  project: defaultproject
  projectID: rx28oml
spec:
  base:
    name: default
    version: snapshot - 2021-10-28T10:49:48Z
  defaultAddons:
    enableIngress: true
    enableLogging: true
    enableMonitoring: true
  drift: {}
  psp:
    enabled: true
    names:
    - rafay-privileged-psp
    scope: Cluster
  sharing: {}
  version: v2
