apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  description: df. erd wrdwdf v
  id: x3mxvkr
  modifiedAt:
    nanos: 644566000
    seconds: 1636361128
  name: test
  project: defaultproject
  projectID: rx28oml
spec:
  base:
    name: default
    version: snapshot - 2021-11-08T03:56:06Z
  defaultAddons:
    enableIngress: true
    enableLogging: true
    enableMonitoring: true
  drift: {}
  psp:
    enabled: true
    names:
    - rafay-privileged-psp
    scope: Cluster
  sharing:
    enabled: true
    projects:
    - id: 7w2lnkp
      name: three
    - id: 4qkolkn
      name: two
  version: new-ver
