apiVersion: opa.k8smgmt.io/v3
kind: Constraint
metadata:
  id: qkogl2n
  modifiedAt:
    nanos: 3183000
    seconds: 1635340256
  name: catorgorg
  project: defaultproject
  projectID: rx28oml
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/catorgorg/constraint.yml
    options: {}
    type: Yaml
  templateName: k8sallowedlimits
