apiVersion: opa.k8smgmt.io/v3
kind: Constraint
metadata:
  name: repo-is-openpolicyagent
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/repo-is-openpolicyagent/constraint.yml
    options: {}
    type: Yaml
  templateName: k8sallowedlimits
