apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: new-sync-job
  project: defaultproject
spec:
  active: true
  sharing:
    enabled: false
  stages:
  - config:
      destinationRepo:
        repository: opatest
        revision: main
      gitToSystemSync: true
      includedResources:
      - name: '*'
      sourceAsDestination: true
      sourceRepo:
        path:
          name: folder3
        repository: opatest
        revision: main
      systemToGitSync: true
    name: test-ankit
    type: SystemSync
  triggers:
  - config:
      repo:
        paths:
        - name: folder3
        provider: Github
        repository: opatest
        revision: main
    name: test
    type: Webhook
