apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  description: Workload snapshot created for OPA Constraint Template
  id: pkzjgmv
  modifiedAt:
    nanos: 433081000
    seconds: 1634757169
  name: opa-template-k8sallowedrepos
  project: defaultproject
  projectID: rx28oml
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/opa-template-k8sallowedrepos/temp.yml
    options: {}
    type: Yaml
  namespace: rafay-system
  sharing: {}
  version: opa-template-k8sallowedrepos-v1
